// Generated by CoffeeScript 1.12.5
(function () {
  let $ = document.querySelector.bind(document);
  let storage = chrome.storage.sync;
  let catchError = function (f) {
    return function () {
      if (chrome.runtime.lastError) {
        return alert(chrome.runtime.lastError.string);
      } else if (f) {
        return f.apply(this, arguments);
      }
    };
  };

  storage.get(
    {
      sites: [],
      holdTime: 2,
      cooldown: 5,
      backdropOpacity: 0.8,
      explanation: "Default",
    },
    catchError(function (args) {
      let site;

      // Get the sites from the text area
      $("#sites").value = (function () {
        let ref = args.sites;
        let results = [];
        for (let i = 0; i < ref.length; i++) {
          site = ref[i];
          results.push(site.hostSuffix);
        }

        return results;
      })().join("\n");

      $("#holdTime").value = args.holdTime;
      $("#cooldown").value = args.cooldown;
      $("#explanation").value = args.explanation;

      return ($("#dimming").value = Math.round(args.backdropOpacity * 100));
    })
  );

  $("#sites").addEventListener("input", function () {
    var site;

    let sites = (function () {
      var i, len, ref, results;
      ref = $("#sites").value.split("\n");
      results = [];
      for (let i = 0; i < ref.length; i++) {
        site = ref[i];
        if (site) {
          results.push({
            hostSuffix: site,
          });
        }
      }
      return results;
    })();

    return storage.set(
      {
        sites: sites,
      },
      catchError()
    );
  });

  $("#holdTime").addEventListener("input", function () {
    return storage.set(
      {
        holdTime: parseFloat($("#holdTime").value),
      },
      catchError()
    );
  });

  $("#cooldown").addEventListener("input", function () {
    return storage.set(
      {
        cooldown: parseFloat($("#cooldown").value),
      },
      catchError()
    );
  });

  $("#dimming").addEventListener("input", function () {
    return storage.set(
      {
        backdropOpacity: parseFloat($("#dimming").value) / 100,
      },
      catchError()
    );
  });

  $("#explanation").addEventListener("input", function () {
    return storage.set(
      {
        explanation: $("#explanation").value,
      },
      catchError()
    );
  });
}).call(this);
